# Generated by Django 5.1.7 on 2025-03-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='create_date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
