# Generated by Django 5.1.7 on 2025-03-30 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_remove_question_down_remove_question_up_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='subject',
            new_name='title',
        ),
    ]
