# Generated by Django 5.1.7 on 2025-03-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_rename_subject_question_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='create_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='create_date',
            field=models.DateTimeField(null=True),
        ),
    ]
