# Generated by Django 5.1.7 on 2025-03-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0005_alter_answer_create_date_alter_question_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='unlike',
            field=models.IntegerField(default=0),
        ),
    ]
